version: '3'

services:
  semantic-search:
    image: semantic-search:latest
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    ports:
      - "8000:8000" 
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
      - celery-worker
      - redis

  celery-worker:
    image: celery-worker:latest
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    command: ["celery", "-A", "semantic_search.app.celery", "worker", "--loglevel=info"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - QDRANT_HOST=qdrant
    depends_on:
      - redis
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

  redis:
    image: redis:latest
    ports:
      - "6379:6379"